### PR TITLE
HRoomMap

### PR DESCRIPTION
**Pull request by ruangustavo**
The parser for floor height header, it allows you find all valid tiles of a room as well the amount

### CODE REVIEW

**Comment by sirjonasxx** [comment]
hmm, I would prefer a direct-mapped datastructure instead of a list of all tiles
actually, the very result of ```map = packet.read_string().split("\r")``` might be enough already

also, i think x & y are inverted. It's a bit confusing but for example the following;

```
xx1x0xx\r
xx0000x\r
xx0000x\r
xxxxxxx\r
```

has the "1" on x:2,y:0
while x:2,y:0 would currently return 'x'
(not 100% sure)


is_walkable is not really an applicable name, a more valid name would be has_tile. For checking if a tile is walkable, it may be more useful to parse the heightmap and keep track of HeightMapUpdate, although this is not 100% correct it will give a better indication

**Review by sirjonasxx — CHANGES_REQUESTED** [review]
see comments above

**Comment by ruangustavo** [comment]
hey jonas, thank you for replying me! what do you mean by "direct-mapped datastructure"? moreover, what about the x and y, they are 0-N indexed, just as works to moveavatar etc

**Comment by sirjonasxx** [comment]
as it currently is, to check if a tile exists you do the following:
``` def is_walkable(self, x, y):
        for tile in self.tiles:
            if (tile.x, tile.y) == (x, y):
                return True
        return False        
```
this means you need to iterate over every single tile in the list to evaluate this function

a better method would be something where you do self.tiles[x][y] or self.tiles[(x,y)], to instantly get the tile at that position

**Pull request closed without merging**
